[package]
name = "iced-clock"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["canvas", "tokio"] }
chrono = "0.4.39"

[profile.dev]
opt-level = 1
overflow-checks = false
